plugins:
  - checksum: 66c46aeb66f8183c60f1a11525a21dc9a5e6c69e42c8af24586d65557cdf952dd359a5c25321575ff4b975ee09c00adc080b109bb8bcc293eef60dad75223d19
    path: .yarn/plugins/prepare-manifest.cjs
    spec: "https://yarn-plugins.jvdwaal.nl/prepare-manifest/0.2.2"

yarnPath: .yarn/releases/yarn-4.4.0.cjs

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.yarnpkg.com"
npmPublishAccess: public
