name: Validate PR
on:
  pull_request:

permissions:
  contents: read
  
jobs:
  Build-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install
        run: yarn

      - name: Build 🔧
        run: yarn build:all


